<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
	<EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="Material.Icons.WPF" Version="3.0.2" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Dialogs\AlterRuleDialog.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\Dialogs\AlterRuleDialog.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <ItemGroup>
		  <ModFile Include="$(TargetDir)$(TargetName)$(TargetExt)" />
	  </ItemGroup>
	  <Copy SourceFiles="@(ModFile)" DestinationFolder="$(SolutionDir)Main/bin/$(Configuration)/$(TargetFramework)/Modules" SkipUnchangedFiles="true" />
  </Target>

  <Target Name="_addDrawingReference" AfterTargets="ResolveTargetingPackAssets">
    <ItemGroup>
      <Reference Condition="'%(Reference.FileName)' == 'PresentationCore'" Include="%(Reference.RootDir)%(Reference.Directory)System.Drawing.Common.dll;&#xD;&#xA;                          %(Reference.RootDir)%(Reference.Directory)System.Private.Windows.GdiPlus.dll" />
    </ItemGroup>
  </Target>

</Project>
