<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
	<EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Material.Icons.WPF" Version="2.1.10" />
	  <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
	  <PackageReference Include="Prism.Wpf" Version="9.0.537" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Core\Core.csproj" />
	  <ProjectReference Include="..\Main\Main.csproj" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<ModFile Include="$(TargetDir)$(TargetName)$(TargetExt)"/>
			<SetFile Include="Version.Git.Settings.yaml"/>
		</ItemGroup>
		<Copy SourceFiles="@(ModFile);@(SetFile)"
			  DestinationFolder="$(SolutionDir)Main/bin/Debug/net8.0-windows/Modules"
			  SkipUnchangedFiles="true"/>
	</Target>
	
</Project>
